BUCKETS = ('<svg viewBox="0 0 780 330" role="img" aria-label="schema で持つべきものを、文書・投影・設定の3つに仕分ける">'
 '<text x="20" y="22" font-size="11" font-weight="700" fill="var(--muted)">仕分けの問い　── どれも、決まったことから出てくる</text>'
 '<rect x="20" y="34" width="740" height="70" fill="none" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="34" y="54" font-size="9.5" fill="currentColor">① 軸を持つか　── 何に依存して変わるかを言えるか（論点14）</text>'
 '<text x="34" y="70" font-size="9.5" fill="currentColor">② 人の承認を要する意思決定を運ぶか（論点7）</text>'
 '<text x="34" y="86" font-size="9.5" fill="currentColor">③ 形（出す先の成果物）のためだけに型になっていないか（論点8）</text>'
 '<text x="400" y="54" font-size="9.5" fill="currentColor">④ 変更の記録と承認が要るか（論点9 ・ 12）</text>'
 '<text x="400" y="70" font-size="9.5" fill="currentColor">⑤ 規則と引き方を宣言する必要があるか（論点6 ・ 13）</text>'
 '<text x="400" y="90" font-size="8.5" fill="var(--muted)">①③が要。②④⑤は、型として持つ値打ちを測る</text>'
 '<rect x="20" y="126" width="235" height="150" fill="none" stroke="var(--key)" stroke-width="1.8"/>'
 '<text x="137" y="148" text-anchor="middle" font-size="11" font-weight="700" fill="var(--key)">文書　── schema で持つ</text>'
 '<text x="34" y="170" font-size="9" fill="var(--muted)">承認を通り、変更の記録を持ち、</text>'
 '<text x="34" y="186" font-size="9" fill="var(--muted)">軸で引ける</text>'
 '<text x="34" y="212" font-size="9.5" fill="currentColor">spec　／　coding　／　ADR</text>'
 '<text x="34" y="232" font-size="9.5" fill="var(--add)">knowledge　？</text>'
 '<text x="34" y="256" font-size="8.5" fill="var(--muted)">knowledge は承認を通るが、軸が言えていない</text>'
 '<rect x="273" y="126" width="235" height="150" fill="none" stroke="var(--add)" stroke-width="1.5"/>'
 '<text x="390" y="148" text-anchor="middle" font-size="11" font-weight="700" fill="var(--add)">投影　── 出す先の形</text>'
 '<text x="287" y="170" font-size="9" fill="var(--muted)">中身は別の型が持ち、</text>'
 '<text x="287" y="186" font-size="9" fill="var(--muted)">これは出し方だけを言う</text>'
 '<text x="287" y="212" font-size="9.5" fill="var(--add)">skill　？　　agent　？</text>'
 '<text x="287" y="238" font-size="8.5" fill="var(--muted)">SKILL.md を出すためだけの型なら、</text>'
 '<text x="287" y="254" font-size="8.5" fill="var(--muted)">それは形で切っている（論点8 に触れる）</text>'
 '<rect x="526" y="126" width="234" height="150" fill="none" stroke="var(--soft)" stroke-width="1.4"/>'
 '<text x="643" y="148" text-anchor="middle" font-size="11" font-weight="700" fill="var(--muted)">設定　── schema で持たない</text>'
 '<text x="540" y="170" font-size="9" fill="var(--muted)">道具の動かし方であって、</text>'
 '<text x="540" y="186" font-size="9" fill="var(--muted)">何が正しいかを述べていない</text>'
 '<text x="540" y="212" font-size="9.5" fill="var(--muted)">hook　？</text>'
 '<text x="540" y="238" font-size="8.5" fill="var(--muted)">ただし「いつ何を検めるか」を言うなら、</text>'
 '<text x="540" y="254" font-size="8.5" fill="var(--muted)">それは規則の側（論点6 の名簿）</text>'
 '<line x1="20" y1="292" x2="760" y2="292" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="312" font-size="9.5" fill="var(--muted)">？ は<b>まだ当てていない</b>ということ ──'
 '<tspan fill="var(--key)" font-weight="700">当てる前に、置き場所を決め打ちしない</tspan></text>'
 '</svg>',
 '<b>schema で持つかどうかは、3つの行き先に仕分けて決める。</b>'
 '文書（承認を通り、変更の記録を持ち、軸で引ける）／投影（出す先の形だけを言う）／設定（道具の動かし方）── '
 '<b>いま確かなのは spec ・ coding ・ ADR だけで、残る4つは当てていない。</b>')
