CODCUT = ('<svg viewBox="0 0 780 300" role="img" aria-label="CodingSchema は種別で切り、CodingSkills は層で切っている。同じ対象を別の向きで切っている">'
 '<text x="20" y="24" font-size="11.5" font-weight="700" fill="var(--del)">捨てる形　── いまの CodingSchema（種別で切る）</text>''<text x="330" y="100" text-anchor="end" font-size="10" font-weight="700" fill="var(--del)">✕ 捨てる</text>'
 '<rect x="20" y="38" width="82" height="40" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="61" y="63" text-anchor="middle" font-size="8.5" fill="var(--muted)">architecture</text>'
 '<rect x="108" y="38" width="82" height="40" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="149" y="56" text-anchor="middle" font-size="8.5" fill="var(--muted)">coding-</text>'
 '<text x="149" y="70" text-anchor="middle" font-size="8.5" fill="var(--muted)">standard</text>'
 '<rect x="196" y="38" width="82" height="40" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="237" y="63" text-anchor="middle" font-size="8.5" fill="var(--muted)">tech-stack</text>'
 '<rect x="284" y="38" width="84" height="40" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="326" y="56" text-anchor="middle" font-size="8.5" fill="var(--muted)">test-</text>'
 '<text x="326" y="70" text-anchor="middle" font-size="8.5" fill="var(--muted)">standard</text>'
 '<text x="20" y="100" font-size="9.5" fill="var(--del)">1つの文書に、言語のことも用途のことも混ざる</text>'
 '<text x="20" y="118" font-size="9.5" fill="var(--muted)">「テスト規約」と言っても、言語の話か用途の話かは開けるまで分からない</text>'
 '<line x1="390" y1="14" x2="390" y2="150" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="410" y="24" font-size="11.5" font-weight="700" fill="var(--key)">採る形　── CodingSkills に合わせる（層で切る）</text>'
 '<rect x="410" y="38" width="80" height="40" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="450" y="56" text-anchor="middle" font-size="9.5" fill="var(--key)">言語</text>'
 '<text x="450" y="70" text-anchor="middle" font-size="8" fill="var(--muted)">綴り ・ 失敗 ・ 並行</text>'
 '<rect x="496" y="38" width="88" height="40" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="540" y="56" text-anchor="middle" font-size="9.5" fill="var(--key)">アーキ</text>'
 '<text x="540" y="70" text-anchor="middle" font-size="8" fill="var(--muted)">層 ・ 依存の向き</text>'
 '<rect x="590" y="38" width="88" height="40" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="634" y="56" text-anchor="middle" font-size="9.5" fill="var(--key)">言語 × アーキ</text>'
 '<text x="634" y="70" text-anchor="middle" font-size="8" fill="var(--muted)">表し方 ・ 置き場所</text>'
 '<rect x="684" y="38" width="76" height="40" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="722" y="56" text-anchor="middle" font-size="9.5" fill="var(--key)">用途</text>'
 '<text x="722" y="70" text-anchor="middle" font-size="8" fill="var(--muted)">契約 ・ 保証</text>'
 '<text x="410" y="100" font-size="9.5" fill="var(--key)">1つの文書は、1つの層でしか成り立たないことだけを持つ</text>'
 '<text x="410" y="118" font-size="9.5" fill="var(--muted)">種別（コーディング ・ テスト …）は、前置きの欄で持つ</text>'
 '<line x1="20" y1="140" x2="760" y2="140" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="164" font-size="11" font-weight="700" fill="var(--muted)">同じ対象を、別の向きで切っている</text>'
 '<rect x="120" y="182" width="120" height="26" fill="none" stroke="var(--soft)"/>'
 '<text x="180" y="199" text-anchor="middle" font-size="9" fill="var(--muted)">コーディング</text>'
 '<rect x="250" y="182" width="120" height="26" fill="none" stroke="var(--soft)"/>'
 '<text x="310" y="199" text-anchor="middle" font-size="9" fill="var(--muted)">テスト</text>'
 '<rect x="380" y="182" width="120" height="26" fill="none" stroke="var(--soft)"/>'
 '<text x="440" y="199" text-anchor="middle" font-size="9" fill="var(--muted)">アーキテクチャ</text>'
 '<rect x="510" y="182" width="120" height="26" fill="none" stroke="var(--soft)"/>'
 '<text x="570" y="199" text-anchor="middle" font-size="9" fill="var(--muted)">技術スタック</text>'
 '<text x="20" y="199" font-size="9.5" fill="var(--del)">種別　→</text>'
 '<text x="20" y="232" font-size="9.5" fill="var(--key)">層　↓</text>'
 '<text x="120" y="232" font-size="9" fill="var(--muted)">言語　── 綴りと書式 ／ テストの仕組み ／ 標準の道具</text>'
 '<text x="120" y="250" font-size="9" fill="var(--muted)">アーキ　── 層と責務 ／ 確かめる単位の境界</text>'
 '<text x="120" y="268" font-size="9" fill="var(--muted)">用途　── 契約と起動 ／ 保証する振る舞い ／ 採る依存</text>'
 '<text x="20" y="290" font-size="9.5" fill="var(--key)">同じ「テスト」でも、層が違えば宣言する中身の構造が違う</text>'
 '</svg>',
 '<b>切り方が90度ずれている。</b>CodingSchema は種別で切り、CodingSkills は層で切る ── '
 '<b>同じ「テスト規約」でも、言語の層では「テストが走る仕組み」、用途の層では「何を保証するか」で、構造が違う。</b>'
 '種別で切ると、その2つが同じ名前の文書に入る。'
 '<b>左は捨てる形として残してある</b> ── もともと CodingSkills に合わせる想定だったので、'
 '4種の表現で schema を作り直すことはしない。')
