COMPOSE = ('<svg viewBox="0 0 780 400" role="img" aria-label="保存された schema と、書くときに合成されて AI へ渡る description の実際の中身">'
 '<defs><marker id="cp1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker></defs>'
 '<text x="20" y="22" font-size="11" font-weight="700" fill="var(--muted)">保存の形（schema に在るもの）</text>'
 '<rect x="20" y="32" width="300" height="150" fill="none" stroke="currentColor" stroke-width="1.4"/>'
 '<text x="32" y="52" font-size="9.5" fill="var(--muted)">"title": {</text>'
 '<text x="42" y="70" font-size="9.5" fill="var(--muted)">"type": "string",</text>'
 '<text x="42" y="88" font-size="9.5" fill="currentColor">"description": "シナリオの題",</text>'
 '<text x="42" y="110" font-size="9.5" fill="var(--add)">"x-prompt-write":</text>'
 '<text x="52" y="126" font-size="9" fill="var(--muted)">"振る舞いを述べる一文。実装名を含めない",</text>'
 '<text x="42" y="148" font-size="9.5" fill="var(--key)">"x-prompt-query":</text>'
 '<text x="52" y="164" font-size="9" fill="var(--muted)">"題だけを読む。対応は別の欄で見る"</text>'
 '<text x="32" y="178" font-size="9.5" fill="var(--muted)">}</text>'
 '<line x1="320" y1="90" x2="368" y2="90" stroke="var(--key)" stroke-width="1.5" marker-end="url(#cp1)"/>'
 '<text x="344" y="80" text-anchor="middle" font-size="9" font-weight="700" fill="var(--key)">書く射影</text>'
 '<text x="380" y="22" font-size="11" font-weight="700" fill="var(--key)">書くときに AI へ渡る形</text>'
 '<rect x="380" y="32" width="380" height="150" fill="none" stroke="var(--key)" stroke-width="1.8"/>'
 '<text x="392" y="52" font-size="9.5" fill="var(--muted)">"title": {</text>'
 '<text x="402" y="70" font-size="9.5" fill="var(--muted)">"type": "string",</text>'
 '<text x="402" y="88" font-size="9.5" fill="var(--muted)">"description":</text>'
 '<rect x="410" y="96" width="340" height="76" fill="none" stroke="var(--add)" stroke-width="1" stroke-dasharray="3 2"/>'
 '<text x="420" y="112" font-size="9.5" fill="var(--add)">これは：<tspan fill="currentColor">シナリオの題</tspan></text>'
 '<text x="420" y="130" font-size="9.5" fill="var(--add)">書き方：<tspan fill="currentColor">振る舞いを述べる一文にする</tspan></text>'
 '<text x="420" y="148" font-size="9.5" fill="var(--add)">禁じ手：<tspan fill="currentColor">実装の名前を含めない</tspan></text>'
 '<text x="420" y="166" font-size="9.5" fill="var(--add)">例：<tspan fill="currentColor">予約を確定できる</tspan></text>'
 '<text x="380" y="196" font-size="9" fill="var(--muted)">1行1役割。<tspan fill="var(--key)">行の頭のラベルが、その行が何かを言う</tspan></text>'
 '<line x1="20" y1="212" x2="760" y2="212" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="234" font-size="11" font-weight="700" fill="var(--del)">×　つないで散文にした場合</text>'
 '<rect x="20" y="244" width="360" height="76" fill="none" stroke="var(--del)" stroke-width="1.4"/>'
 '<text x="32" y="264" font-size="9.5" fill="var(--muted)">"description": "シナリオの題です。振る舞いを</text>'
 '<text x="32" y="280" font-size="9.5" fill="var(--muted)">述べる一文にしてください。なお実装の名前は</text>'
 '<text x="32" y="296" font-size="9.5" fill="var(--muted)">含めないでください。たとえば「予約を確定</text>'
 '<text x="32" y="312" font-size="9.5" fill="var(--muted)">できる」のように書きます"</text>'
 '<text x="20" y="342" font-size="9.5" fill="var(--del)">どこまでが説明で、どこからが指示かの区切りが無い</text>'
 '<text x="20" y="358" font-size="9.5" fill="var(--del)">長くなるほど、後ろの一文が効かなくなる</text>'
 '<text x="20" y="380" font-size="9.5" fill="var(--muted)">機械で切り出せないので、渡した中身を後から確かめられない</text>'
 '<text x="410" y="234" font-size="11" font-weight="700" fill="var(--key)">読むときは、渡すものが変わる</text>'
 '<rect x="410" y="244" width="350" height="60" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="422" y="264" font-size="9.5" fill="var(--key)">これは：<tspan fill="currentColor">シナリオの題</tspan></text>'
 '<text x="422" y="284" font-size="9.5" fill="var(--key)">読み方：<tspan fill="currentColor">題だけを読む。対応は別の欄で見る</tspan></text>'
 '<text x="410" y="326" font-size="9.5" fill="var(--muted)">「書き方」は載らない ── 読む射影と書く射影は</text>'
 '<text x="410" y="342" font-size="9.5" fill="var(--muted)">別の出力先だからである</text>'
 '<text x="410" y="364" font-size="9.5" fill="var(--key)">いま何をしているかを、AI に判断させない</text>'
 '<text x="410" y="386" font-size="9" fill="var(--muted)">中身を JSON 文字列にしてもよい。合成した文字列は保存されないので、正本は変わらない</text>'
 '</svg>',
 '<b>合成するのは、文をつなぐことではない。</b>「これは」「書き方」「禁じ手」「例」というラベルを頭に置いた行を、'
 '決まった順で並べるだけである ── <b>行の頭がその行の役割を言うので、途中から読んでも形が保つ。</b>'
 'そして書くときと読むときでは、載せる行が違う。')
