COMPOSE = ('<svg viewBox="0 0 780 450" role="img" aria-label="x-prompt 自体を構造で持ち、書くときはラベル行か JSON 文字列へ合成する">'
 '<defs><marker id="cp1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker></defs>'
 '<text x="20" y="22" font-size="11" font-weight="700" fill="var(--muted)">保存の形　── 指示そのものを構造で持つ</text>'
 '<rect x="20" y="32" width="300" height="196" fill="none" stroke="currentColor" stroke-width="1.4"/>'
 '<text x="32" y="50" font-size="9" fill="var(--muted)">"title": {</text>'
 '<text x="42" y="66" font-size="9" fill="var(--muted)">"type": "string",</text>'
 '<text x="42" y="82" font-size="9" fill="currentColor">"description": "シナリオの題",</text>'
 '<text x="42" y="102" font-size="9" fill="var(--add)">"x-prompt-write": {</text>'
 '<text x="54" y="118" font-size="9" fill="var(--muted)">"how": "振る舞いを述べる一文にする",</text>'
 '<text x="54" y="134" font-size="9" fill="var(--muted)">"forbidden": ["実装の名前を含めない"],</text>'
 '<text x="54" y="150" font-size="9" fill="var(--muted)">"example": "予約を確定できる" },</text>'
 '<text x="42" y="172" font-size="9" fill="var(--key)">"x-prompt-query": {</text>'
 '<text x="54" y="188" font-size="9" fill="var(--muted)">"read": "題だけを読む",</text>'
 '<text x="54" y="204" font-size="9" fill="var(--muted)">"related": "対応は別の欄で見る" }</text>'
 '<text x="32" y="222" font-size="9" fill="var(--muted)">}</text>'
 '<text x="20" y="248" font-size="9" fill="var(--key)">欄が分かれているので、<tspan font-weight="700">「例が無い」を規則で数えられる</tspan></text>'
 '<line x1="320" y1="120" x2="366" y2="120" stroke="var(--key)" stroke-width="1.5" marker-end="url(#cp1)"/>'
 '<text x="343" y="112" text-anchor="middle" font-size="9" font-weight="700" fill="var(--key)">書く射影</text>'
 '<text x="380" y="22" font-size="11" font-weight="700" fill="var(--key)">書くときに AI へ渡る形　── どちらでもよい</text>'
 '<text x="380" y="42" font-size="9.5" font-weight="700" fill="var(--add)">○ ラベル行　── 欄名を表示名に置き換える</text>'
 '<rect x="380" y="48" width="380" height="76" fill="none" stroke="var(--add)" stroke-width="1.5"/>'
 '<text x="390" y="64" font-size="9" fill="var(--muted)">"description":</text>'
 '<text x="400" y="80" font-size="9" fill="var(--add)">これは：<tspan fill="currentColor">シナリオの題</tspan></text>'
 '<text x="400" y="94" font-size="9" fill="var(--add)">書き方：<tspan fill="currentColor">振る舞いを述べる一文にする</tspan></text>'
 '<text x="400" y="108" font-size="9" fill="var(--add)">禁じ手：<tspan fill="currentColor">実装の名前を含めない</tspan>　例：<tspan fill="currentColor">予約を確定できる</tspan></text>'
 '<text x="380" y="146" font-size="9.5" font-weight="700" fill="var(--key)">○ JSON 文字列　── 宣言された欄名を、そのまま鍵にする</text>'
 '<rect x="380" y="152" width="380" height="76" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="390" y="168" font-size="9" fill="var(--muted)">"description": "{\\\\"description\\\\": \\\\"シナリオの題\\\\",</text>'
 '<text x="402" y="184" font-size="9" fill="var(--muted)">\\\\"how\\\\": \\\\"振る舞いを述べる一文にする\\\\",</text>'
 '<text x="402" y="200" font-size="9" fill="var(--muted)">\\\\"forbidden\\\\": [\\\\"実装の名前を含めない\\\\"],</text>'
 '<text x="402" y="216" font-size="9" fill="var(--muted)">\\\\"example\\\\": \\\\"予約を確定できる\\\\"}"</text>'
 '<text x="380" y="248" font-size="9" fill="var(--muted)">どちらも<tspan fill="var(--key)">保存の欄を並べ替えただけ</tspan>。合成のときに文を切り分けない</text>'
 '<line x1="20" y1="266" x2="760" y2="266" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="288" font-size="11" font-weight="700" fill="var(--del)">×　指示を1つの文字列に押し込む</text>'
 '<rect x="20" y="298" width="340" height="60" fill="none" stroke="var(--del)" stroke-width="1.4"/>'
 '<text x="32" y="316" font-size="9" fill="var(--muted)">"x-prompt-write": "振る舞いを述べる一文。</text>'
 '<text x="32" y="332" font-size="9" fill="var(--muted)">実装名を含めない。例：予約を確定できる"</text>'
 '<text x="32" y="350" font-size="9" fill="var(--del)">句読点が、意味の境界を兼ねてしまっている</text>'
 '<text x="20" y="380" font-size="9" fill="var(--del)">「例が無い」「禁じ手が無い」を数えられない</text>'
 '<text x="20" y="396" font-size="9" fill="var(--del)">合成のたびに、文を切り分けることになる</text>'
 '<text x="20" y="416" font-size="9" fill="var(--muted)">句点の打ち方が変わると、切り分けの結果も変わる</text>'
 '<text x="400" y="288" font-size="11" font-weight="700" fill="var(--key)">読むときは、渡す欄が変わる</text>'
 '<rect x="400" y="298" width="360" height="52" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="412" y="316" font-size="9" fill="var(--key)">これは：<tspan fill="currentColor">シナリオの題</tspan></text>'
 '<text x="412" y="334" font-size="9" fill="var(--key)">読み方：<tspan fill="currentColor">題だけを読む（対応は別の欄で見る）</tspan></text>'
 '<text x="400" y="370" font-size="9" fill="var(--muted)">載るのは x-prompt-query の欄だけ ── 書く指示は載らない</text>'
 '<text x="400" y="392" font-size="9" fill="var(--key)">いま何をしているかを、AI に判断させない</text>'
 '<text x="400" y="414" font-size="9" fill="var(--muted)">合成した文字列は保存されない。正本は、左上のままである</text>'
 '</svg>',
 '<b>指示の中に意味の境界があるなら、それは構造で持つ。</b>'
 '句読点で区切ると、境界が文字列の中に隠れ、<b>「例が無い」を数えることも、合成を機械で閉じることもできなくなる。</b>'
 '欄に分けておけば、合成は<b>並べ替えるだけ</b>になり、ラベル行にするか JSON にするかは出力先の選択にすぎない。')
