COMPOSE = ('<svg viewBox="0 0 780 440" role="img" aria-label="保存された schema と、書くときに合成されて AI へ渡る2つの形（ラベル行と JSON 文字列）、および散文にした場合と読むときの形">'
 '<defs><marker id="cp1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker></defs>'
 '<text x="20" y="22" font-size="11" font-weight="700" fill="var(--muted)">保存の形（schema に在るもの。人が読むのはこれ）</text>'
 '<rect x="20" y="32" width="290" height="150" fill="none" stroke="currentColor" stroke-width="1.4"/>'
 '<text x="32" y="52" font-size="9.5" fill="var(--muted)">"title": {</text>'
 '<text x="42" y="70" font-size="9.5" fill="var(--muted)">"type": "string",</text>'
 '<text x="42" y="88" font-size="9.5" fill="currentColor">"description": "シナリオの題",</text>'
 '<text x="42" y="110" font-size="9.5" fill="var(--add)">"x-prompt-write":</text>'
 '<text x="52" y="126" font-size="9" fill="var(--muted)">"振る舞いを述べる一文。実装名を含めない",</text>'
 '<text x="42" y="148" font-size="9.5" fill="var(--key)">"x-prompt-query":</text>'
 '<text x="52" y="164" font-size="9" fill="var(--muted)">"題だけを読む。対応は別の欄で見る"</text>'
 '<text x="32" y="178" font-size="9.5" fill="var(--muted)">}</text>'
 '<line x1="310" y1="104" x2="356" y2="104" stroke="var(--key)" stroke-width="1.5" marker-end="url(#cp1)"/>'
 '<text x="333" y="96" text-anchor="middle" font-size="9" font-weight="700" fill="var(--key)">書く射影</text>'
 '<text x="370" y="22" font-size="11" font-weight="700" fill="var(--key)">書くときに AI へ渡る形　── どちらでもよい</text>'
 '<text x="370" y="40" font-size="9.5" font-weight="700" fill="var(--add)">○ ラベル行</text>'
 '<rect x="370" y="46" width="390" height="74" fill="none" stroke="var(--add)" stroke-width="1.5"/>'
 '<text x="380" y="62" font-size="9" fill="var(--muted)">"description":</text>'
 '<text x="390" y="78" font-size="9" fill="var(--add)">これは：<tspan fill="currentColor">シナリオの題</tspan></text>'
 '<text x="390" y="92" font-size="9" fill="var(--add)">書き方：<tspan fill="currentColor">振る舞いを述べる一文にする</tspan></text>'
 '<text x="390" y="106" font-size="9" fill="var(--add)">禁じ手：<tspan fill="currentColor">実装の名前を含めない</tspan>　例：<tspan fill="currentColor">予約を確定できる</tspan></text>'
 '<text x="370" y="140" font-size="9.5" font-weight="700" fill="var(--key)">○ JSON 文字列</text>'
 '<rect x="370" y="146" width="390" height="66" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="380" y="162" font-size="9" fill="var(--muted)">"description": "{\\"これは\\": \\"シナリオの題\\",</text>'
 '<text x="392" y="178" font-size="9" fill="var(--muted)">\\"書き方\\": \\"振る舞いを述べる一文にする\\",</text>'
 '<text x="392" y="194" font-size="9" fill="var(--muted)">\\"禁じ手\\": \\"実装の名前を含めない\\", \\"例\\": \\"予約を確定できる\\"}"</text>'
 '<text x="370" y="228" font-size="9" fill="var(--muted)">中身は同じ。<tspan fill="var(--key)">切り出しは JSON が確実</tspan>で、<tspan fill="var(--del)">引用符のぶんだけ かさむ</tspan></text>'
 '<line x1="20" y1="244" x2="760" y2="244" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="266" font-size="11" font-weight="700" fill="var(--del)">×　つないで散文にした場合</text>'
 '<rect x="20" y="276" width="350" height="74" fill="none" stroke="var(--del)" stroke-width="1.4"/>'
 '<text x="32" y="294" font-size="9" fill="var(--muted)">"description": "シナリオの題です。振る舞いを述べる</text>'
 '<text x="32" y="310" font-size="9" fill="var(--muted)">一文にしてください。なお実装の名前は含めないで</text>'
 '<text x="32" y="326" font-size="9" fill="var(--muted)">ください。たとえば「予約を確定できる」のように</text>'
 '<text x="32" y="342" font-size="9" fill="var(--muted)">書きます"</text>'
 '<text x="20" y="370" font-size="9" fill="var(--del)">どこまでが説明で、どこからが指示かの区切りが無い</text>'
 '<text x="20" y="386" font-size="9" fill="var(--del)">長くなるほど、後ろの一文が効かなくなる</text>'
 '<text x="20" y="406" font-size="9" fill="var(--muted)">機械で切り出せないので、渡した中身を後から確かめられない</text>'
 '<text x="400" y="266" font-size="11" font-weight="700" fill="var(--key)">読むときは、渡すものが変わる</text>'
 '<rect x="400" y="276" width="360" height="52" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="412" y="294" font-size="9" fill="var(--key)">これは：<tspan fill="currentColor">シナリオの題</tspan></text>'
 '<text x="412" y="312" font-size="9" fill="var(--key)">読み方：<tspan fill="currentColor">題だけを読む。対応は別の欄で見る</tspan></text>'
 '<text x="400" y="348" font-size="9" fill="var(--muted)">「書き方」は載らない ── 読む射影と書く射影は、別の出力先である</text>'
 '<text x="400" y="370" font-size="9" fill="var(--key)">いま何をしているかを、AI に判断させない</text>'
 '<text x="400" y="392" font-size="9" fill="var(--muted)">どの形を選んでも、合成した文字列は保存されない ──</text>'
 '<text x="400" y="408" font-size="9" fill="var(--muted)">正本は、左上の「保存の形」のままである</text>'
 '</svg>',
 '<b>合成するのは、文をつなぐことではない。</b>ラベルを頭に置いた行を並べるか、JSON 文字列にするか ── '
 '<b>どちらも中身は同じで、切り出しやすさと かさ が違うだけである。</b>'
 '散文だけが、区切りを持たないので後から確かめられない。'
 'そして書くときと読むときでは、載せる行が違う。')
