RULECORE = ('<svg viewBox="0 0 780 300" role="img" aria-label="規則の塊は、全種類で同じ芯と、種類ごとの欄でできている">'
 '<defs><marker id="rc1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker></defs>'
 '<text x="20" y="22" font-size="11" font-weight="700" fill="var(--muted)">規則1件　── 詳細の塊1つ</text>'
 '<rect x="20" y="34" width="420" height="128" fill="none" stroke="currentColor" stroke-width="1.5"/>'
 '<rect x="34" y="46" width="392" height="30" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="44" y="66" font-size="9.5" fill="var(--key)">### ID　　言明（検査できる最小の一文）</text>'
 '<rect x="34" y="82" width="392" height="26" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="44" y="99" font-size="9.5" fill="var(--key)">検証方法　＝　走らせる命令 ＋ 落ちない部分の見る箇所</text>'
 '<rect x="34" y="114" width="392" height="36" fill="none" stroke="var(--add)" stroke-width="1.5" stroke-dasharray="4 3"/>'
 '<text x="44" y="130" font-size="9.5" fill="var(--add)">種類ごとの欄（水準 ・ 根拠 ・ 例外 ・ 適合例 …）</text>'
 '<text x="44" y="144" font-size="8.5" fill="var(--muted)">何を持つかは、種別の雛形が定める</text>'
 '<text x="460" y="60" font-size="9.5" fill="var(--key)">芯　── 全種類で同じ</text>'
 '<text x="460" y="76" font-size="8.5" fill="var(--muted)">rule-core が定める</text>'
 '<text x="460" y="130" font-size="9.5" fill="var(--add)">種類ごと　── 15の種で違う</text>'
 '<text x="460" y="146" font-size="8.5" fill="var(--muted)">style ・ acceptance ・ contract …</text>'
 '<line x1="440" y1="62" x2="452" y2="62" stroke="var(--key)" stroke-width="1.2"/>'
 '<line x1="440" y1="132" x2="452" y2="132" stroke="var(--add)" stroke-width="1.2"/>'
 '<text x="20" y="188" font-size="11" font-weight="700" fill="var(--muted)">塊の外に置くもの</text>'
 '<rect x="20" y="200" width="330" height="48" fill="none" stroke="var(--key)" stroke-width="1.4"/>'
 '<text x="34" y="220" font-size="9.5" fill="var(--key)">出典の表　── 同じ ID の行に、原典と裏づけを書く</text>'
 '<text x="34" y="238" font-size="8.5" fill="var(--muted)">全規則ぶんが1つの表に並び、原典の重なりが見える</text>'
 '<rect x="380" y="200" width="360" height="48" fill="none" stroke="var(--soft)" stroke-width="1.3" stroke-dasharray="4 3"/>'
 '<text x="394" y="220" font-size="9.5" fill="var(--muted)">規則の一覧　── 書かない。塊から導出する</text>'
 '<text x="394" y="238" font-size="8.5" fill="var(--muted)">どの列を持つかは、種別の雛形が宣言する</text>'
 '<line x1="20" y1="264" x2="760" y2="264" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="284" font-size="9.5" fill="var(--muted)">これが「15の種それぞれに必須の欄をどう決めるか」の答えになる ──'
 '<tspan fill="var(--key)" font-weight="700">芯が共通の必須欄で、残りが種ごとの欄</tspan></text>'
 '</svg>',
 '<b>規則の塊は、芯と種類ごとの欄でできている。</b>'
 'ID ・ 言明 ・ 検証方法 ・ 出典は全種類で同じで、それ以外は種別の雛形が定める ── '
 '<b>schema に落とすとき、芯がそのまま共通の必須欄になる。</b>'
 '出典は塊の外の表に集め、一覧は書かずに塊から導出する。')
