PROMPT = ('<svg viewBox="0 0 780 280" role="img" aria-label="書き方の指示を x- に保存し、構造化出力へ渡すときだけ description へ合成する">'
 '<defs><marker id="pm1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker>'
 '<marker id="pm2" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--del)"/></marker></defs>'
 '<text x="20" y="24" font-size="11.5" font-weight="700" fill="var(--muted)">保存の形（schema）</text>'
 '<rect x="20" y="38" width="240" height="104" fill="none" stroke="currentColor" stroke-width="1.5"/>'
 '<text x="34" y="60" font-size="10" fill="var(--muted)">description</text>'
 '<text x="34" y="76" font-size="9.5" fill="currentColor">この欄が何であるか</text>'
 '<line x1="34" y1="86" x2="246" y2="86" stroke="var(--rule)"/>'
 '<text x="34" y="104" font-size="10" fill="var(--add)">x-prompt-write</text>'
 '<text x="34" y="120" font-size="9.5" fill="var(--muted)">どう書くか</text>'
 '<text x="34" y="136" font-size="9.5" fill="var(--muted)">（x-prompt-query は、どう読むか）</text>'
 '<text x="20" y="170" font-size="10" fill="var(--muted)">説明と指示が、別の欄に分かれている。</text>'
 '<text x="20" y="186" font-size="10" fill="var(--muted)">片方だけを直せる</text>'
 '<rect x="330" y="52" width="150" height="42" fill="none" stroke="var(--del)" stroke-width="1.5"/>'
 '<text x="405" y="70" text-anchor="middle" font-size="10" fill="var(--del)">構造化出力へ渡す</text>'
 '<text x="405" y="86" text-anchor="middle" font-size="9.5" fill="var(--del)">x- は拒まれる</text>'
 '<line x1="260" y1="73" x2="324" y2="73" stroke="var(--del)" stroke-width="1.4" marker-end="url(#pm2)"/>'
 '<text x="330" y="112" font-size="9.5" fill="var(--del)">そのまま渡すと、指示が落ちる</text>'
 '<rect x="330" y="140" width="150" height="42" fill="none" stroke="var(--key)" stroke-width="1.8"/>'
 '<text x="405" y="158" text-anchor="middle" font-size="10" font-weight="700" fill="var(--key)">渡すときに合成</text>'
 '<text x="405" y="174" text-anchor="middle" font-size="9.5" fill="var(--muted)">射影の1つとして扱う</text>'
 '<line x1="260" y1="120" x2="324" y2="155" stroke="var(--key)" stroke-width="1.5" marker-end="url(#pm1)"/>'
 '<text x="540" y="24" font-size="11.5" font-weight="700" fill="var(--muted)">渡す形（構造化出力）</text>'
 '<rect x="540" y="140" width="220" height="60" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="554" y="160" font-size="10" fill="var(--muted)">description</text>'
 '<text x="554" y="176" font-size="9.5" fill="currentColor">この欄が何であるか</text>'
 '<text x="554" y="192" font-size="9.5" fill="var(--add)">＋　どう書くか</text>'
 '<line x1="480" y1="161" x2="534" y2="161" stroke="var(--key)" stroke-width="1.5" marker-end="url(#pm1)"/>'
 '<text x="540" y="220" font-size="10" fill="var(--key)">標準の欄なので、そのまま載る</text>'
 '<text x="540" y="236" font-size="10" fill="var(--muted)">合成するのは渡すときだけで、</text>'
 '<text x="540" y="252" font-size="10" fill="var(--muted)">保存の形は分かれたまま</text>'
 '</svg>',
 '<b>保存の形と、渡す形は別である</b> ── 論点8 で決めたことが、そのままここへ効く。'
 '指示は <code>x-</code> に分けて保存し、構造化出力へ渡すときだけ <code>description</code> へ合成する。'
 '<b>description に直接書くと、説明と指示が1つの文字列になり、片方だけを直せなくなる。</b>')

MIGRATE = ('<svg viewBox="0 0 780 250" role="img" aria-label="欄を足すときは任意にし、壊す変更は新しい型にする">'
 '<defs><marker id="mg1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker>'
 '<marker id="mg2" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--del)"/></marker></defs>'
 '<text x="20" y="24" font-size="11.5" font-weight="700" fill="var(--key)">欄を足す　── 任意にする</text>'
 '<rect x="20" y="40" width="150" height="46" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="95" y="60" text-anchor="middle" font-size="10" fill="var(--muted)">型 v1</text>'
 '<text x="95" y="76" text-anchor="middle" font-size="9" fill="var(--muted)">欄 A ・ B</text>'
 '<rect x="220" y="40" width="150" height="46" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="295" y="60" text-anchor="middle" font-size="10" fill="var(--key)">型 v2</text>'
 '<text x="295" y="76" text-anchor="middle" font-size="9" fill="var(--muted)">欄 A ・ B ・ C（任意）</text>'
 '<line x1="170" y1="63" x2="214" y2="63" stroke="var(--key)" stroke-width="1.4" marker-end="url(#mg1)"/>'
 '<text x="20" y="112" font-size="10" fill="var(--key)">古い document は、そのまま通る</text>'
 '<text x="20" y="128" font-size="10" fill="var(--muted)">移行を書かなくてよい</text>'
 '<line x1="395" y1="14" x2="395" y2="238" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="420" y="24" font-size="11.5" font-weight="700" fill="var(--del)">壊す変更　── 型を分ける</text>'
 '<rect x="420" y="40" width="150" height="46" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="495" y="60" text-anchor="middle" font-size="10" fill="var(--muted)">型 v1</text>'
 '<text x="495" y="76" text-anchor="middle" font-size="9" fill="var(--muted)">そのまま残す</text>'
 '<rect x="610" y="40" width="150" height="46" fill="none" stroke="var(--del)" stroke-width="1.5"/>'
 '<text x="685" y="60" text-anchor="middle" font-size="10" fill="var(--del)">新しい型</text>'
 '<text x="685" y="76" text-anchor="middle" font-size="9" fill="var(--muted)">別の名前で立てる</text>'
 '<line x1="570" y1="63" x2="604" y2="63" stroke="var(--del)" stroke-width="1.4" stroke-dasharray="4 3" marker-end="url(#mg2)"/>'
 '<text x="420" y="112" font-size="10" fill="var(--del)">既存の document は動かさない</text>'
 '<text x="420" y="128" font-size="10" fill="var(--muted)">移す判断は、文書ごとに人がする</text>'
 '<line x1="20" y1="152" x2="760" y2="152" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="176" font-size="10.5" fill="var(--muted)">型は横に増える（論点5 の決まり）。だから<tspan fill="var(--key)" font-weight="700">縦に移す仕掛けを持たなくてよい</tspan>。</text>'
 '<text x="20" y="196" font-size="10.5" fill="var(--muted)">必須の欄を後から足すことだけが、既存の document を壊す ── それを禁じれば、移行は要らなくなる。</text>'
 '<text x="20" y="222" font-size="10" fill="var(--del)">代償：使わなくなった欄が残り続ける。捨てる判断を、別に決めることになる</text>'
 '</svg>',
 '<b>移行が要るのは、必須の欄を後から足したときだけである。</b>任意の欄を足すぶんには、古い document はそのまま通る。'
 '壊す変更をしたくなったら、型を分ける ── <b>型は横に増える、という決まりの直接の帰結である。</b>')

QUERY = ('<svg viewBox="0 0 780 270" role="img" aria-label="構造の式で引く場合と、意味の述語で引く場合の違い">'
 '<text x="20" y="24" font-size="11.5" font-weight="700" fill="var(--muted)">A　構造の式で引く（いまの形）</text>'
 '<rect x="20" y="38" width="340" height="30" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="34" y="58" font-size="9.5" fill="currentColor">content.scenarios.items[?status==\'ACTIVE\'].mark</text>'
 '<text x="20" y="88" font-size="10" fill="var(--muted)">引く側が、構造を知っている必要がある</text>'
 '<text x="20" y="106" font-size="10" fill="var(--muted)">構造が変われば、式も直す</text>'
 '<text x="20" y="124" font-size="10" fill="var(--del)">印・型・軸といった意味は、式の中に埋もれる</text>'
 '<text x="20" y="150" font-size="10" fill="var(--muted)">式で書けるものは何でも引ける ── </text>'
 '<text x="20" y="166" font-size="10" fill="var(--muted)">同じ問いに、何通りもの書き方ができる</text>'
 '<line x1="390" y1="14" x2="390" y2="256" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="418" y="24" font-size="11.5" font-weight="700" fill="var(--key)">C　意味の述語で引く</text>'
 '<rect x="418" y="38" width="342" height="30" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="432" y="58" font-size="9.5" fill="var(--key)">引く（型＝シナリオ、状態＝有効）→ 印の一覧</text>'
 '<text x="418" y="88" font-size="10" fill="var(--key)">引く側は、意味だけを知っていればよい</text>'
 '<text x="418" y="106" font-size="10" fill="var(--muted)">構造が変わっても、述語は変わらない</text>'
 '<text x="418" y="124" font-size="10" fill="var(--key)">規則の判定と、同じ語彙を使う（論点6）</text>'
 '<text x="418" y="150" font-size="10" fill="var(--muted)">述語で書けないものは引けない ── </text>'
 '<text x="418" y="166" font-size="10" fill="var(--muted)">同じ問いには、同じ書き方しかない</text>'
 '<line x1="20" y1="190" x2="760" y2="190" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="214" font-size="10.5" fill="var(--muted)">同じ語彙が、2か所で使われる ── </text>'
 '<text x="20" y="234" font-size="10.5" fill="var(--muted)">規則では「この述語を満たすか」を判定し、取得では「この述語を満たすものを出せ」と引く。</text>'
 '<text x="20" y="256" font-size="10.5" fill="var(--key)">述語を1つ足すと、規則にも取得にも同時に効く。</text>'
 '</svg>',
 '<b>構造の式は、schema が持つ意味（印・型・軸）を知らない。</b>だから引く側が構造を知ることになり、'
 '構造が変われば式も直る。<b>述語で引けば、規則の判定と同じ語彙で引ける</b> ── '
 'そのかわり、述語で書けない取得はできなくなる。')
