MIGTIME = ('<svg viewBox="0 0 780 260" role="img" aria-label="ずれを読むときに検知し、印だけ付け、承認の境目でまとめて当てる">'
 '<defs><marker id="mt1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--muted)"/></marker>'
 '<marker id="mt2" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--add)"/></marker></defs>'
 '<rect x="20" y="60" width="150" height="52" fill="none" stroke="var(--soft)" stroke-width="1.3"/>'
 '<text x="95" y="82" text-anchor="middle" font-size="11" fill="currentColor">読む</text>'
 '<text x="95" y="99" text-anchor="middle" font-size="9" fill="var(--muted)">schema と document を突き合わせる</text>'
 '<rect x="215" y="60" width="150" height="52" fill="none" stroke="var(--add)" stroke-width="1.6"/>'
 '<text x="290" y="82" text-anchor="middle" font-size="11" fill="var(--add)">印を付ける</text>'
 '<text x="290" y="99" text-anchor="middle" font-size="9" fill="var(--muted)">ずれた節に、当てる移行を結ぶ</text>'
 '<rect x="410" y="60" width="150" height="52" fill="none" stroke="var(--soft)" stroke-width="1.3"/>'
 '<text x="485" y="82" text-anchor="middle" font-size="11" fill="currentColor">仕事を続ける</text>'
 '<text x="485" y="99" text-anchor="middle" font-size="9" fill="var(--muted)">古い欄は読めるので、止めない</text>'
 '<rect x="606" y="60" width="154" height="52" fill="none" stroke="var(--key)" stroke-width="1.8"/>'
 '<text x="683" y="82" text-anchor="middle" font-size="11" font-weight="700" fill="var(--key)">承認の境目</text>'
 '<text x="683" y="99" text-anchor="middle" font-size="9" fill="var(--muted)">まとめて見せ、当てる</text>'
 '<line x1="170" y1="86" x2="209" y2="86" stroke="var(--muted)" stroke-width="1.3" marker-end="url(#mt1)"/>'
 '<line x1="365" y1="86" x2="404" y2="86" stroke="var(--muted)" stroke-width="1.3" marker-end="url(#mt1)"/>'
 '<line x1="560" y1="86" x2="600" y2="86" stroke="var(--add)" stroke-width="1.5" marker-end="url(#mt2)"/>'
 '<text x="20" y="40" font-size="11" font-weight="700" fill="var(--muted)">ずれに気づいてから、当てるまで</text>'
 '<line x1="20" y1="132" x2="760" y2="132" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="154" font-size="10.5" fill="var(--del)">×　読んだ瞬間に直しにいく</text>'
 '<text x="20" y="172" font-size="9.5" fill="var(--muted)">仕事の途中で承認を求めることになり、いま何をしていたかが切れる</text>'
 '<text x="20" y="188" font-size="9.5" fill="var(--muted)">断ると、次に読むたびにまた聞かれる</text>'
 '<text x="410" y="154" font-size="10.5" fill="var(--key)">○　印だけ付けて、境目でまとめて出す</text>'
 '<text x="410" y="172" font-size="9.5" fill="var(--muted)">承認の材料に「当てる移行 N 件」が並ぶ（論点7）</text>'
 '<text x="410" y="188" font-size="9.5" fill="var(--muted)">当てるのは状態を変える操作なので、人が通す</text>'
 '<text x="20" y="216" font-size="10" fill="var(--muted)">当てる中身は、schema が宣言している ──'
 '<tspan fill="var(--key)" font-weight="700">AI は推測で直さない</tspan></text>'
 '<text x="20" y="236" font-size="10" fill="var(--muted)">宣言に無い直し方が要るものは、そもそも壊す変更として禁じる（型を分ける）</text>'
 '</svg>',
 '<b>ずれは読むときに分かるが、直すのは読むときではない。</b>'
 '仕事の途中で承認を求めると、いま何をしていたかが切れる ── '
 '<b>印だけ付けて古い欄のまま読み進み、承認の境目でまとめて当てる。</b>'
 '当てる中身は schema が宣言しているので、AI が推測で直すことはない。')
