MIGTIME = ('<svg viewBox="0 0 780 280" role="img" aria-label="Waffle の版を上げない限りずれは起きず、更新のときだけ合わない document を列挙して当てる">'
 '<defs><marker id="mt1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--muted)"/></marker>'
 '<marker id="mt2" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--add)"/></marker></defs>'
 '<text x="20" y="24" font-size="11.5" font-weight="700" fill="var(--key)">ふだん　── Waffle の版が変わらないあいだ</text>'
 '<rect x="20" y="36" width="330" height="56" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="185" y="58" text-anchor="middle" font-size="11" fill="var(--key)">schema と document は、必ず同じ版である</text>'
 '<text x="185" y="78" text-anchor="middle" font-size="9.5" fill="var(--muted)">ずれが起きないので、検知も移行もしない</text>'
 '<text x="20" y="112" font-size="9.5" fill="var(--muted)">読むたびに版を判定しない。仕事の途中で承認を求められることもない</text>'
 '<line x1="20" y1="132" x2="760" y2="132" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="156" font-size="11.5" font-weight="700" fill="var(--add)">Waffle を更新したとき　── ずれが起きるのは、この一瞬だけ</text>'
 '<rect x="20" y="170" width="150" height="52" fill="none" stroke="var(--add)" stroke-width="1.5"/>'
 '<text x="95" y="192" text-anchor="middle" font-size="10.5" fill="var(--add)">列挙する</text>'
 '<text x="95" y="209" text-anchor="middle" font-size="9" fill="var(--muted)">新しい版に合わない document</text>'
 '<rect x="215" y="170" width="160" height="52" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="295" y="192" text-anchor="middle" font-size="10.5" fill="var(--key)">宣言どおりに当てる</text>'
 '<text x="295" y="209" text-anchor="middle" font-size="9" fill="var(--muted)">旧名→新名 ・ 削除 ・ 既定値</text>'
 '<rect x="420" y="170" width="160" height="52" fill="none" stroke="var(--del)" stroke-width="1.5"/>'
 '<text x="500" y="192" text-anchor="middle" font-size="10.5" fill="var(--del)">宣言に無いもの</text>'
 '<text x="500" y="209" text-anchor="middle" font-size="9" fill="var(--muted)">人へ回す。AI は推測しない</text>'
 '<rect x="625" y="170" width="135" height="52" fill="none" stroke="var(--key)" stroke-width="1.8"/>'
 '<text x="692" y="192" text-anchor="middle" font-size="10.5" font-weight="700" fill="var(--key)">承認して確定</text>'
 '<text x="692" y="209" text-anchor="middle" font-size="9" fill="var(--muted)">状態を変える操作である</text>'
 '<line x1="170" y1="196" x2="209" y2="196" stroke="var(--muted)" stroke-width="1.3" marker-end="url(#mt1)"/>'
 '<line x1="375" y1="196" x2="414" y2="196" stroke="var(--muted)" stroke-width="1.3" marker-end="url(#mt1)"/>'
 '<line x1="580" y1="196" x2="619" y2="196" stroke="var(--add)" stroke-width="1.5" marker-end="url(#mt2)"/>'
 '<text x="20" y="248" font-size="10" fill="var(--muted)">更新しない限り、前の版のまま使い続けられる ──'
 '<tspan fill="var(--key)" font-weight="700">後方互換を、実行時に持ち回らなくてよい</tspan></text>'
 '<text x="20" y="268" font-size="10" fill="var(--muted)">担保するのは「1段ぶんの更新」だけである。何段も飛ばすときは、段を順に当てる</text>'
 '</svg>',
 '<b>schema の版は、Waffle の版に従う。</b>更新しない限り schema と document は必ず同じ版なので、'
 '<b>ずれが起きるのは更新した一瞬だけ</b>である ── ふだんは検知も移行も要らない。'
 '更新のときに、合わない document を列挙し、宣言された移行を当て、'
 '<b>宣言に無いものだけを人へ回す。</b>')
