SPECLAYER = ('<svg viewBox="0 0 780 380" role="img" aria-label="spec の3軸は上下関係ではなく、業務を中心に接点と基盤が並ぶ。掛け合わせは掛けた層に書く">'
 '<defs><marker id="sp1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker></defs>'
 '<text x="20" y="22" font-size="11" font-weight="700" fill="var(--muted)">軸　── 上下は無い。1つを固定しても、他が動く</text>'
 '<rect x="300" y="44" width="180" height="66" fill="none" stroke="var(--key)" stroke-width="2"/>'
 '<text x="390" y="68" text-anchor="middle" font-size="12" font-weight="700" fill="var(--key)">業務</text>'
 '<text x="390" y="86" text-anchor="middle" font-size="8.5" fill="var(--muted)">何を成すか</text>'
 '<text x="390" y="101" text-anchor="middle" font-size="8" fill="var(--muted)">接点も基盤も知らない</text>'
 '<rect x="40" y="44" width="180" height="66" fill="none" stroke="currentColor" stroke-width="1.4"/>'
 '<text x="130" y="68" text-anchor="middle" font-size="11" fill="currentColor">接点</text>'
 '<text x="130" y="86" text-anchor="middle" font-size="8.5" fill="var(--muted)">誰に差し出すか</text>'
 '<text x="130" y="101" text-anchor="middle" font-size="8" fill="var(--muted)">人 ／ 別のシステム ／ AI</text>'
 '<rect x="560" y="44" width="180" height="66" fill="none" stroke="currentColor" stroke-width="1.4"/>'
 '<text x="650" y="68" text-anchor="middle" font-size="11" fill="currentColor">基盤</text>'
 '<text x="650" y="86" text-anchor="middle" font-size="8.5" fill="var(--muted)">どこで動かすか</text>'
 '<text x="650" y="101" text-anchor="middle" font-size="8" fill="var(--muted)">満たすべき要件</text>'
 '<line x1="220" y1="77" x2="294" y2="77" stroke="var(--key)" stroke-width="1.5" marker-end="url(#sp1)"/>'
 '<line x1="560" y1="77" x2="486" y2="77" stroke="var(--key)" stroke-width="1.5" marker-end="url(#sp1)"/>'
 '<text x="257" y="68" text-anchor="middle" font-size="8" fill="var(--key)">指す</text>'
 '<text x="523" y="68" text-anchor="middle" font-size="8" fill="var(--key)">指す</text>'
 '<text x="40" y="132" font-size="8.5" fill="var(--muted)">接点と基盤は、互いを知らない ── 並んでいるだけで、上下ではない</text>'
 '<line x1="20" y1="148" x2="760" y2="148" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="170" font-size="11" font-weight="700" fill="var(--muted)">層　── 軸の組み合わせから導出される</text>'
 '<rect x="40" y="184" width="215" height="54" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="147" y="204" text-anchor="middle" font-size="9.5" fill="currentColor">接点だけで決まること</text>'
 '<text x="147" y="222" text-anchor="middle" font-size="8.5" fill="var(--muted)">約束の形（呼び方 ・ 返し方 ・ 失敗）</text>'
 '<rect x="282" y="184" width="215" height="54" fill="none" stroke="var(--key)" stroke-width="1.5"/>'
 '<text x="389" y="204" text-anchor="middle" font-size="9.5" fill="var(--key)">業務だけで決まること</text>'
 '<text x="389" y="222" text-anchor="middle" font-size="8.5" fill="var(--muted)">業務の構造と振る舞い</text>'
 '<rect x="524" y="184" width="215" height="54" fill="none" stroke="var(--soft)" stroke-width="1.2"/>'
 '<text x="631" y="204" text-anchor="middle" font-size="9.5" fill="currentColor">基盤だけで決まること</text>'
 '<text x="631" y="222" text-anchor="middle" font-size="8.5" fill="var(--muted)">容量 ・ 耐障害 ・ 保全の要件</text>'
 '<rect x="150" y="256" width="215" height="54" fill="none" stroke="var(--add)" stroke-width="1.6"/>'
 '<text x="257" y="276" text-anchor="middle" font-size="9.5" fill="var(--add)">業務 × 接点</text>'
 '<text x="257" y="294" text-anchor="middle" font-size="8.5" fill="var(--muted)">この業務を、この接点でどう差し出すか</text>'
 '<rect x="414" y="256" width="215" height="54" fill="none" stroke="var(--add)" stroke-width="1.6"/>'
 '<text x="521" y="276" text-anchor="middle" font-size="9.5" fill="var(--add)">業務 × 基盤</text>'
 '<text x="521" y="294" text-anchor="middle" font-size="8.5" fill="var(--muted)">この業務に、どの要件が要るか</text>'
 '<text x="20" y="334" font-size="9" fill="var(--add)">掛けた層は、どちらの軸にも属さないことを書く ── 片方だけでは決まらない</text>'
 '<text x="20" y="354" font-size="9" fill="var(--muted)">層はあらかじめ並べない。<tspan fill="var(--key)" font-weight="700">軸の組み合わせが現れた数だけ在る</tspan>（論点16）</text>'
 '<text x="20" y="374" font-size="9" fill="var(--muted)">接点 × 基盤 の層は、いまのところ現れていない ── 現れたら、そのとき足す</text>'
 '</svg>',
 '<b>3つの軸に上下は無い。</b>業務が中心にあるのは「他が業務を指す」からで、'
 '接点が業務の下、基盤がそのまた下、という積み方ではない ── <b>接点と基盤は互いを知らず、並んでいるだけである。</b>'
 '掛け合わせは、どちらの軸にも属さないことを書く場所として、掛けた層に置く。')
