TOOLS = ('<svg viewBox="0 0 780 340" role="img" aria-label="能力は業務の層、差し出し方は業務×接点の層、script は接点のアダプタ">'
 '<defs><marker id="tl1" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--key)"/></marker>'
 '<marker id="tl2" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
 '<path d="M0 0 L10 5 L0 10 z" fill="var(--muted)"/></marker></defs>'
 '<text x="20" y="22" font-size="10.5" font-weight="700" fill="var(--key)">業務の層　── Waffle ができること</text>'
 '<rect x="20" y="34" width="240" height="86" fill="none" stroke="var(--key)" stroke-width="1.8"/>'
 '<text x="34" y="56" font-size="9.5" fill="currentColor">ずれを検める　／　骨格を作る</text>'
 '<text x="34" y="74" font-size="9.5" fill="currentColor">値を書き込む　／　描画する</text>'
 '<text x="34" y="98" font-size="8.5" fill="var(--muted)">受け入れ基準を持ち、承認を通る</text>'
 '<text x="34" y="112" font-size="8.5" fill="var(--muted)">＝ ここが spec の主題</text>'
 '<text x="300" y="22" font-size="10.5" font-weight="700" fill="var(--add)">業務 × 接点の層　── どう差し出すか</text>'
 '<rect x="300" y="34" width="460" height="86" fill="none" stroke="var(--add)" stroke-width="1.8"/>'
 '<text x="314" y="54" font-size="9.5" fill="var(--add)">CLI　＝　命令の名前 ・ 引数 ・ 終了コード</text>'
 '<text x="314" y="72" font-size="9.5" fill="var(--add)">MCP　＝　道具の名前 ・ 入力の形 ・ 返す形</text>'
 '<text x="314" y="90" font-size="9.5" fill="var(--add)">Hook　＝　<tspan font-weight="700">どの事象で起きるか</tspan> ・ 止めるか通すか ・ 何を返すか</text>'
 '<text x="314" y="110" font-size="8.5" fill="var(--muted)">同じ能力を、3つの接点で差し出す ── トリガーの仕様は、ここに書く</text>'
 '<line x1="260" y1="77" x2="294" y2="77" stroke="var(--key)" stroke-width="1.5" marker-end="url(#tl1)"/>'
 '<line x1="20" y1="140" x2="760" y2="140" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="162" font-size="10.5" font-weight="700" fill="var(--muted)">実装　── spec ではない</text>'
 '<rect x="20" y="176" width="215" height="60" fill="none" stroke="var(--soft)" stroke-width="1.3"/>'
 '<text x="127" y="198" text-anchor="middle" font-size="9.5" fill="currentColor">CLI のアダプタ</text>'
 '<text x="127" y="216" text-anchor="middle" font-size="8.5" fill="var(--muted)">引数を受けて、能力を呼ぶ</text>'
 '<rect x="250" y="176" width="215" height="60" fill="none" stroke="var(--soft)" stroke-width="1.3"/>'
 '<text x="357" y="198" text-anchor="middle" font-size="9.5" fill="currentColor">MCP のアダプタ</text>'
 '<text x="357" y="216" text-anchor="middle" font-size="8.5" fill="var(--muted)">道具の呼び出しを受けて、能力を呼ぶ</text>'
 '<rect x="480" y="176" width="280" height="60" fill="none" stroke="var(--add)" stroke-width="1.5"/>'
 '<text x="620" y="198" text-anchor="middle" font-size="9.5" fill="var(--add)">Hook の script　＝ 接点のアダプタ</text>'
 '<text x="620" y="216" text-anchor="middle" font-size="8.5" fill="var(--muted)">事象を受けて、CLI か MCP の能力を呼ぶだけ</text>'
 '<line x1="127" y1="176" x2="127" y2="126" stroke="var(--muted)" stroke-width="1.2" marker-end="url(#tl2)"/>'
 '<line x1="357" y1="176" x2="357" y2="126" stroke="var(--muted)" stroke-width="1.2" marker-end="url(#tl2)"/>'
 '<line x1="620" y1="176" x2="620" y2="126" stroke="var(--muted)" stroke-width="1.2" marker-end="url(#tl2)"/>'
 '<text x="20" y="264" font-size="9" fill="var(--del)">× script が、そこでしか無い処理を持つ</text>'
 '<text x="20" y="280" font-size="8.5" fill="var(--muted)">Hook からしか使えない能力ができ、CLI からも MCP からも呼べない</text>'
 '<text x="400" y="264" font-size="9" fill="var(--key)">○ script は呼ぶだけ</text>'
 '<text x="400" y="280" font-size="8.5" fill="var(--muted)">能力は1つで、差し出し口が3つになる</text>'
 '<line x1="20" y1="296" x2="760" y2="296" stroke="var(--rule)" stroke-width="1"/>'
 '<text x="20" y="316" font-size="9" fill="var(--muted)">いまの hook は <tspan fill="var(--key)">usecaseRef</tspan> と'
 '<tspan fill="var(--key)">scriptRef</tspan> を持っている ── 呼ぶ先と、呼ぶ道具が分かれている</text>'
 '<text x="20" y="332" font-size="9" fill="var(--muted)">この形が、すでに「script は呼ぶだけ」に近い</text>'
 '</svg>',
 '<b>能力は業務の層、差し出し方は業務 × 接点の層、script は実装のアダプタである。</b>'
 'CLI ・ MCP ・ Hook は<b>同じ能力を差し出す3つの接点</b>で、'
 '<b>「どの事象で起きるか」は Hook という接点の仕様</b>だから、業務 × 接点の層に書く。'
 'script がそこでしか無い処理を持つと、<b>Hook からしか使えない能力</b>ができてしまう。')
